### ISSUE TITLE
[OpenGL]Rendering issues in Metal Gear Solid.

### ISSUE THREAD

**Issue by kenshen112** [libretro/beetle-psx-libretro#233]
Metal Gear Solid: the first cutscenes are fu*** up and are unviewable, the submarine is a black rectangle and Snake is a broken texture and a half. I have made a video to show the issue with the game. 

https://www.youtube.com/watch?v=v0ThS5BATgg - What the game is supposed to look like.

https://youtu.be/fhZJIpDSLuI - What Beetle psx hw's OpenGL Renderer looks like.

**Comment by rz5** [comment]
Same problem that causes #224, those cutscenes are rendered in real-time and wobbly/motion-blurry effects probably rely on mask bit emulation, which the GL renderer can't do at the moment.

**Comment by Papermanzero** [comment]
Should also be fixed with mask bit implemted in opengl.

**Comment by medievil1** [comment]
just updating that bug is still present...12/2/2018

**Comment by Papermanzero** [comment]
Sure. Someone has to implement following features:

https://github.com/libretro/beetle-psx-libretro/issues/412
https://github.com/libretro/beetle-psx-libretro/issues/413
https://github.com/libretro/beetle-psx-libretro/issues/414

**Comment by tgrant4800** [comment]
I apologize for the necro, but the issue is still present currently but in a somewhat different fashion than op described. For example, for the opening cutscene before you get to the main menu, the submarine floating through empty water looks fine, but the entire left side of the screen looks like it's incorrectly rendering. Even with the text that appears on the screen, when an audio stutter happens the text kinda ghosts somewhat. Like you put two mirrors facing eachother and drew the result or called a phone in the same room and put them both on speaker. The cutscenes are turned into an eyesore and I don't think that's how they're supposed to work.
