### ISSUE TITLE
Crash Team Racing Getting Invisible Lines All Over the place

### ISSUE THREAD

**Issue by Kristijan1001** [libretro/beetle-psx-libretro#323]
For Some Reason i get invisible lines and the life of me i cant fix it.
If i disable PGXP it gets fixed ,but then there are moving textures all over the place. The thing is i found a video of the same game with PGXP and it doesnt have that issuse i really dont know how other can i fix it,

They are all over the place, Using Vulcan but same on OpenGL, i tried PCSX-R the issuse is not there. But on Retroarch is all over. 

Picture:

![](https://i.imgur.com/QUGbJ8G.jpg)

![](https://i.imgur.com/rWRggZm.jpg)

The video i saw:

https://www.youtube.com/watch?v=VkmphxVmA8w

**Comment by saftle** [comment]
When you tried Vulkan, did you change the renderer and retroarch's driver, or just the renderer? You have to set both to Vulkan or else it'll default always to your retroarch driver. I tried it on Vulkan recently (both renderer and driver) and I don't think I saw those lines.

**Comment by iCatButler** [comment]
It's a problem in the GTE's NCLIP operation. PGXP allows smaller triangles to be drawn, these would usually become degenerate (collapse into points or lines) on standard PS1 hardware and be rejected by NCLIP, so PGXP passes its own modified result.

It looks like some modifications have been made to the NCLIP function in GTE.cpp since PGXP was first integrated, they appear to be related to a speed hack implementation. The calculation is being performed again and the result overwrites what was originally the output, this means PGXP isn't able to bias the result for small triangles.

I don't know which of the two standard calculations is the intended implementation, though whichever is chosen should be overridden by PGXP as was happening before.

**Comment by Kristijan1001** [comment]
@saftle did you mean setting to vulkan in retro arch driver menu ? Cause i just tried it and same results :*(  Can you please test again and see if u dont have those lines and send me the config i would really appreciate it.

@iCatButler so is there any way to fix this ? Because its really bad with it, specially in a moving state its all over :( Thanks !

Here is an other screen shot of it.
![](https://i.imgur.com/6FjJeXX.png)

**Comment by simias** [comment]
@iCatButler we had accuracy regressions in the GTE code (even with all hacks disabled) which prompted me to revert a lot of code to the way it was upstream. I still tried to reintegrate PGXP as best as I could but maybe something broke then? I'll have to have a look at that NCLIP implementation to figure out what's going on.

**Comment by iCatButler** [comment]
@Kristijan1001 yes, it should be a relatively simple fix.

@simias that makes sense. Looking at the file history I can see how it might have happened.

With the hacks there were two code paths, the original one calculated `sum`, applied the PGXP override and checked the result for overflow before assigning it to `MAC[0]`. The other performed the calculation and overflow test inline with the result going to `MAC[0]`.

When they were reverted the two appear to have gotten mixed up. I think it should be safe to change the second calculation back to `MAC[0] = sum;`, which should restore the PGXP integration.

**Comment by simias** [comment]
Okay, sorry about that, I'll try to fix it this weekend.

**Comment by Kristijan1001** [comment]
@iCatButler @simias Thanks Alot ! Will be looking forward to it , should i find the updated core in the nightly builds x64 folder if it gets fixed ?

**Comment by simias** [comment]
@Kristijan1001 I believe it should be

**Comment by simias** [comment]
I think that fixes it (and it still passes the GTE accuracy tests too!).

**Comment by twinaphex** [comment]
Cool, this fixes a graphics glitch I saw in Ridge Racer Revolution as well. It would always try to draw a couple of blue lines on the road wherever you would drive, and this glitch would only happen with PGXP + perspective correction enabled. That is now fixed it appears. Great job.

**Comment by Kristijan1001** [comment]
@simias What should i download , becuase i just went into the x64 seciton of nightly builds and downloaded mednafen_hw core, but it is still not working. Also now there is only option to chose between hardware and software in renderer and no OpenGL,Vulcan etc.

**Comment by simias** [comment]
@Kristijan1001 I couldn't tell you, maybe @twinaphex or somebody more familiar with the way the buildbot works could tell you.

**Comment by twinaphex** [comment]
@Kristijan1001 the buildbot has not yet had time to recompile the latest beetle psx core, so just be patient. Maybe check it again tomorrow.

**Comment by Kristijan1001** [comment]
Can confirm its now working perfectly ! @simias thanks alot, also why are there no other renderers to pick up other than software and hardware ?

**Comment by bearoso** [comment]
I've noticed this is still there at git head after the fix:
![final fantasy vii disc 1 -180408-151611-small](https://user-images.githubusercontent.com/16159164/38472126-af9eab3c-3b40-11e8-9ace-40bbd661138e.png)
![final fantasy vii disc 1 -180408-151726-small](https://user-images.githubusercontent.com/16159164/38472129-b56fb380-3b40-11e8-9b94-6158a8cbf983.png)
Appears in Software and Vulkan renderers. Turning on the PGXP precision option closes the gaps, but then there's z-fighting at the same locations. Most noticeable in FF7 fighting at the beach spots.

**Comment by trostboot** [comment]
Curiously, this issue is still present in Xenogears in the software renderer only (gl and vulkan work fine). 
It's easiest to spot on the world map, just panning the camera around will do the trick.

![xenogears ntsc-u -180417-125640](https://user-images.githubusercontent.com/17594477/38867042-21623802-4243-11e8-9c35-dee0048d0909.png)
Higher internal res for better visibility:
![xenogears ntsc-u -180417-130053](https://user-images.githubusercontent.com/17594477/38867067-34f5f228-4243-11e8-843d-9e42b6a5e6b0.png)

This is with the latest beetle hw core. I would have liked to test an older one, but there doesn't seem to be an archive of older core builds anywhere.

**Comment by simias** [comment]
Do you remember it not doing that before? Does it only do it when PGXP is enabled?

I know some game exhibit seams even on real hardware. Tomb Raider would be an example. The very low precision of PSX 3D operations leads to these issues.

**Comment by trostboot** [comment]
I've never played it before using beetle, so I don't know if that's a recent occurence (hence why I wanted to test older builds).
It only happens with PGXP enabled (just memory only is enough), and only on the sw renderer. I can test it out on real hardware if need be, however.

**Comment by iCatButler** [comment]
The software renderer doesn't use the high precision vertex positions, but with PGXP enabled the emulator will still be using them to bias the results of NCLIP, that's likely to be causing this error.

In theory the game may be using the results to determine LoD for the terrain, using failed NCLIP by primitives too small to be represented using native fixed point to determine when to combine them into larger ones. In this case it thinks they're fine but when the software renderer tries to draw them they've collapsed into a 1D line or point.

Ideally PGXP should be disabled when using the software renderer, none of the features like high precision vertices and perspective correct texturing are implemented by it anyway.

**Comment by twinaphex** [comment]
@iCatButler On that subject, it is possible to make some kind of optional hack that could force level of detail to be always at the highest detail level regardless of distance by way of some GTE hack? What other enhancement-like features would be possible? Is it possible to come up with a way to have higher draw distances in a game-agnostic way by hacking up certain GTE functions?

**Comment by trostboot** [comment]
> none of the features like high precision vertices and perspective correct texturing are implemented by it anyway.

Right, that was the impression I was under and why I left the option on when switching between renderers, until I ran into this particular issue with Xenogears.

In addition to automatically disabling it, should probably also include a short tooltip in the option explaining that it's both disabled and unimplemented in the sw renderer to avoid any confusion. If that's possible, I see there aren't any descriptions for any core options.

**Comment by iCatButler** [comment]
@twinaphex I'm not aware of any specific GTE operations directly linked to draw distances or LoD. Though, with the necessary exception of NCLIP, I've tried to avoid PGXP feeding back into the emulator to minimise polluting non-graphics related data.

There are GTE functions linked to fog rendering that could be manipulated to output different values, these might even be used to calculate distance for LoD transitions in some games. Although I doubt there is a single convention used for all games in this matter, I don't think Sony provided common libraries for it, meaning it would probably be reliant on per-game hacks.

There's probably scope for an entirely new project disassembling PS1 games to see how each one ticks and applying hacks to increase framerate and draw distances. The GTE operations would maybe provide a good point of entry because they're used for well defined tasks like lerping animation frames or projection which would give a rough idea of where to start looking.
